config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :listings
  resources :requests
  resources :reviews
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/dashboard", to: "pages#dashboard" ,as: :dashboard
  post "/requests/:id/accept", to: "requests#accept", as: :accept_request
  get "/profile", to: "pages#profile"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  validates :price, presence: true
  #Ex:- :default =>''

  def user
    User.find_by(id: self.user_id)
  end

  def requests
    Request.where(listing_id: self.id)
  end

  def reviews
    Review.where(listing_id: self.id)
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :message, presence: true
  validates :user_id, presence: true, uniqueness: { scope: :listing_id }
  validates :listing_id, uniqueness: true, presence: true, uniqueness: { scope: :user_id }

  def user
    User.find_by(id: self.user_id)
  end

  def listing
    Listing.find_by(id: self.listing_id)
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :listing
    validates :comment, presence: true
    validates :rating, presence: true
    validates :user_id, presence: true 
    validates :listing_id, presence: true

    def listing
        Listing.find_by(id: self.listing_id)
    end

    def customer
        User.find_by(id: self.user_id)
    end

    def user
        User.find_by(id: self.listing_id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
          has_many :listings, dependent: :destroy
          has_many :requests, dependent: :destroy
          has_many :reviews, dependent: :destroy
          validates :first_name, presence: true
          validates :last_name, presence: true
          validates :email, presence: true
          validates :bio, length: { maximum: 500}

          def full_name
            "#{first_name} #{last_name}"
          end

          def listings
            Listing.where(user_id: self.id)
          end

          def requests
            Request.where(user_id: self.id)
          end

          def reviews
            Review.where(user_id: self.id)
          end

          def average_rating
            if self.reviews.count > 0
              (self.reviews.sum(:rating) / self.reviews.count).round(2)
            else
              0
            end
          end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio, :avatar_url])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio, :avatar_url])
  end
end 

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    def index
        @listings = Listing.all
    end

    def show
        @review = Review.new

        @listing = Listing.find(params[:id])
        @request = Request.new
        @this_request = @listing.requests.find_by(user_id: current_user.id)
        @user = current_user

    end

    def new
        @listing = Listing.new
    end
    def create
        
        @listing = Listing.new(listing_params)
        @listing.user = current_user
        if @listing.save
            redirect_to listing_path(@listing)
        else
            render :new
        end
    end

    def edit
        @listing = Listing.find(params[:id])
    end

    def update
        @listing = Listing.find(params[:id])
        @listing.update(listing_params)
        flash[:notice] = "Listing successfully updated."
        redirect_to listing_path(@listing)
    end

    def destroy
        @listing = Listing.find(params[:id])
        @listing.destroy
        flash[:notice] = "Listing successfully deleted."
        redirect_to dashboard_path
    end

    private

    def listing_params
        params.require(:listing).permit(:title, :content, :availability,:price)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def dashboard
    @user = current_user
    @listings = @user.listings
    @requests = Request.where(listing_id: @listings.pluck(:id))
    @reviews = Review.where(listing_id: @listings.pluck(:id))
  end

  def profile
    @user = current_user
    @average_rating = @user.average_rating
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: :destroy

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request.save
    redirect_to listing_path(@request.listing)

  end

  def destroy
    @request.destroy
    flash[:notice] = "Request successfully deleted."
    redirect_to dashboard_path
  end

  def accept
    @request = Request.find(params[:id])
    @request.accepted = true
    @request.save
    redirect_to dashboard_path
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:message, :listing_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        @review.user = current_user
        @review.save
        redirect_to dashboard_path
    end

    private

    def review_params
        params.require(:review).permit(:comment, :rating, :listing_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAFriend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="text-dark bg-white" style="height: 100vh;">
    <%=render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<div class="container p-5 bg-danger w-50 mt-3 border border-3 border-primary">
  <h1 class="text-light"> Edit listing</h1>
  <%=simple_form_for @listing, method: :patch do |f|%>
    <%=f.input :title, class: "form-control border border-danger"%>
    <%=f.label :content, "description"%>
    <%=f.text_area :content, class: "form-control border border-danger"%>
    <%=f.input :price ,class: "border border-outline-danger"%>
    <%=f.input :availability%>
    <%=f.submit :update, class: "btn btn-primary"%>
  <%end%>
</div>

app/views/listings/index.html.erb
<<<<<<< HEAD
<div class="container">

      <% @listings.each do |listing| %>
     <div class="card" style="width: 300px;">
  <img class="card-img-top object-fit-fill" style="height: 200px" src="<%= listing.image_url %>" alt="Card image cap">
  <div class="card-body">
    <h4> <%= listing.title %> </h4>
    <p class="card-text"><%= listing.content %></p>
  </div>
</div>
        <% end %>
=======
<div class="container d-flex flex-wrap align-items-center bg-white gap-3 justify-content-center">
  <h1 class="py-5 w-100 text-center ">Available friends</h1>
  <% @listings.each do |listing| %>
    <div class="card mb-3 border border-danger bg-light text-primary p-3 shadow" style="width: 300px;">
      <img class="card-img-top object-fit-fill border border-primary mb-3" style="height: 200px" src="<%= listing.image_url %>" alt="Card image cap">
      <div class="card-body ">
        <h4 class="d-inline-block text-truncate" style="max-width: 250px;"> <%= listing.title %> </h4>
        <div></div>
        <p class="card-text d-inline-block text-truncate" style="max-width: 250px;"><%= listing.content %></p>
        <p class="card-text">$<%=listing.price%> /Hour</p>
        <a href="listings/<%=listing.id%>" class="btn btn-primary w-100 mb-3 " >Request</a>
        <div class=" d-flex gap-2 align-items-center mb-2">
          <div style="height: 25px; width:25px;"><img class="rounded-circle w-100 h-100 object-fit-cover"src="<%=listing.user.avatar_url%>" alt=""></div>
          <small class="text-muted"><%=listing.user.full_name%></small></div>
        <p class="card-text w-100 text-end text-secondary"><small><%=listing.created_at.to_date%></small></p>

      </div>
    </div>
  <% end %>
>>>>>>> 56a960c4cd5851fa781bc1a0378c8d4be5a18125
</div>

app/views/listings/new.html.erb
<div class="container p-5 bg-danger w-50 mt-3">
  <h1 class="text-light">Create a listing</h1>
  <%=simple_form_for @listing do |f|%>
    <%=f.input :title, class: "form-control border border-danger"%>
    <%=f.label :content, "description"%>
    <%=f.text_area :content, class: "form-control border border-danger"%>
    <%=f.input :price ,class: "border border-outline-danger"%>
    <%=f.input :availability%>
    <%=f.submit :create, class: "btn btn-primary"%>
  <%end%>
</div>

app/views/listings/show.html.erb
<div class="container p-3">
  <div class="d-flex h-100 gap-3 ">
    <div class="col-4 h-100 border border-primary"><img class="w-100" src="<%= @listing.image_url ? @listing.image_url : "https://i.imgflip.com/1i34wa.jpg"%>" alt=""></div>
    <div class="col-8 h-100">
      <div class="row h-100">
        <div class="col">
          <div class="card w-100">
            <div class="card-body border border-danger">
              <div class="d-flex justify-content-between">
                <div class="d-flex align-items-center gap-3 w-75">
                  <h5 class="card-title fs-2 text-primary"><%= @listing.title%></h5>
                  <p class="card-text fs-5 text-secondary "><%= @listing.availability ? "Available" : "Not available"%></p>
                </div>
                <div class="d-flex align-items-center gap-2 p-2">
                  <%if @this_request && @this_request.user_id == current_user.id%>
                    <button type="button" class="btn btn-outline-success disabled" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Sent
                    </button>
                  <%elsif @listing.user_id == current_user.id%>

                    <%= link_to "Edit",edit_listing_path, class: "btn btn-outline-primary"%>

                  <%else%>
                    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Request
                    </button>
                  <%end%>
                  <button type="button" class="btn btn-outline-info">
                    <i class="fa-regular fa-bookmark "></i>
                  </button>
                </div>
              </div>
              <p class="card-text text-primary"><%= @listing.content%></p>
              <div class="d-flex align-items-center">
                <p class="card-text fs-5 "></p>
              </div>
              <div class="d-flex align-items-center justify-content-between">
                <p class="card-text fs-5 text-secondary">$<%=@listing.price%>/Hour</p>
                <p class="card-text fs-5 text-secondary"><small><%=@listing.created_at.strftime("%F")%></small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @listing.user.id != current_user.id%>
      <div class="bg-danger p-3 mt-3">
        <h4 class="text-white my-4">Send a review</h4>
        <%= simple_form_for @review  do |f|%>
        <%= f.input :comment%>
        <%= f.input :rating%>
        <%= f.hidden_field :listing_id, value: @listing.id, class: "form-control border border-danger" %>
        <%= f.hidden_field :customer_id, value: current_user.id %>
        <%= f.submit "Send", class: "btn btn-primary"%>
      <%end%>
      <%end%>
      </div>
      
    </div>
  </div>
  <!-- Button trigger modal -->
  <!-- Modal -->
  <!-- request modal -->
  <div class="modal"  id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="request">
    <div class="modal-dialog border border-danger">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Send a request</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for @request do |f| %>
            <%= f.input :message%>
            <%= f.hidden_field :listing_id, value: @listing.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="modal-footer">
              <%= f.submit "Send", class: "btn btn-outline-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/pages/dashboard.html.erb
<div class="container h-100 py-3">
  <h1 class = "mb-3">Hello <%= current_user.full_name %></h1>
  <div class="row h-100 gap-3">
    <div class="col-12 col-md-6 border border-danger rounded bg-light shadow-sm p-3" id="requests">
      <h4>Latest requests</h4>
      <%= render(RequestComponent.with_collection(@requests)) %>
    </div>
    <div style="max-height: 300px;" class="col border bg-light border-danger shadow-sm overflow-auto p-3 rounded" id="reviews">
        <h4>Latest reviews</h4>

      <%= render(ReviewComponent.with_collection(@reviews)) %>
    </div>
    <div class="col-12 border border-danger rounded bg-light shadow-sm p-3" id="listings">
      <div class="d-flex justify-content-between align-items-center p-2">
        <div>
          <h4>My listings</h4>
        </div>
        <div><%= link_to 'Create listing', new_listing_path, class: "btn btn-primary" %></div>
      </div>
      <%= render(ListingsComponent.new(listings: @listings))%>
    </div>
    <!--request modal-->
  </div>
  <!--request modal-->
</div>

app/views/pages/home.html.erb
<div>
  <div class="home-banner">
    <div class="container">
      <div class="home-cta">
        <h1 class="pt-3">AmigoRental</h1>
        <p>You don't have friends, don't worry, we got you!<br>
           Rent a friend now and change you status from Foreveralone to Neveralone!</p>
        <a class="btn btn-danger" href="/listings">Get a friend</a>
      </div>
    </div>
  </div>
</div>
<div id="what-we-do" class="mt-6 mx-6">
  <h4 class="d-flex justify-content-center">
    Wait a minute who are we ?
  </h4>
  <%# <div id="wam" class ="d-flex align-items-end flex-column" >
<img></img>
  </div> %>
  <div class="d-flex justify-content-center my-2">
    <span id ="devider"></span>
  </div>
  <p class="d-flex justify-content-center"> We provide friendship for anyone anywhere, because everyone deserves a friend.</p>
</div>
<div class="footer mt-6 d-flex justify-content-center">
  <div class="footer-links">
    <a href="#"><i class="fa-solid fa-person"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="d-flex flex-row">
  <div class="h-100"><%=render "shared/sidebar" %></div>
  <div class="d-flex flex-column me-3">
    <div class="d-flex justify-content-between w-100 my-3 mx-4 gap-3">
      <div class="px-3 border bg-light border-danger rounded g-3 w-50">
        <h4 class="text-primary py-2">Bio</h4>
        <p class="text-primary"><%= @user.bio%></p>
      </div>
      <div class="bg-light border border-danger px-2 rounded">
        <h4 class="text-primary py-2 ">Things I like</h4>
        <a class="text-primary my-2" href="https://www.youtube.com/watch?v=Ulz7r_uA6xc&ab_channel=AdultSwim">Human music 🎵</a> <br>
        <a class="text-primary my-2" href="https://www.imdb.com/title/tt0114814/">Usual Suspect 🎥</a> <br>
        <a class="text-primary my-2" href="https://www.goodreads.com/book/show/4865.How_to_Win_Friends_and_Influence_People"> How to make friends... 📖</a>
      </div>
      <div class="border bg-light border-danger me-5 p-3 d-flex flex-column justify-content-evenly align-items-center">
        <h5 class="w-100">Average rating</h5>
        <div class="d-flex align-items-center gap-2">
                  <h1><i class="fa-solid fa-star text-info"></i></h1>

                  <h1 class="text-primary"><%= @average_rating%></h1>

        </div>
      </div>
    </div>
        <h1 class="ms-3">Gallery</h1>
    <div class="gallery p-3">
        <div class="gallery-item border border-danger shadow">
          <img src="https://media.newyorker.com/photos/5b96bac5db10027e03a43bf1/master/w_1920,c_limit/Lambert_Bojack_Horseman_01.jpg" class="d-block w-100 h-100 object-fix-cover" alt="...">
        </div>
        <div class="gallery-item border border-danger shadow">
          <img src="https://pbs.twimg.com/media/Bx4v1OVIIAA3AKH.jpg" alt="...">
        </div>
        <div class="gallery-item border border-danger shadow">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR3eZxX4r50qoPeHkHKDDZLJ_1WvU71x569A&usqp=CAU" class="d-block w-100 h-100 object-fix-cover" alt="...">
        </div>
        <div class="gallery-item border border-danger shadow">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCBnr-oa9wGtnDjIpZxc6zs_22uEA7_I0O-w&usqp=CAU" class="d-block w-100 h-100 object-fix-cover" alt="...">
        </div>
    </div>
    <script>
      $(document).ready(function(){
        $('.carousel').carousel();
      });
    </script>
  </div>

app/views/shared/_carousel.html.erb
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <h2 class="navbar-brand">
      AmigoRental
    </h2>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", "/", class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Friend list", "/listings", class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Notifications", "#", class: "nav-link text-white" %>
          </li> 
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end " aria-labelledby="navbarDropdown">
              <a href="#" class="dropdown-item text-primary"><%=current_user.first_name%> <%=current_user.last_name%></a>
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item text-primary" %>
              <%= link_to "Profile", "/profile", class: "dropdown-item text-primary"%>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-primary" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id ="container" class="h-100 w-20" >
  <div id="sidebar" class="h-100 d-flex flex-column flex-shrink-0 p-3 bg-light " style="width: 280px;">
    <div class="d-flex justify-content-center flex-column align-items-center">
      <div class="sidebar-avatar rounded-circle">
        <img class="border rounded-circle object-fit-cover" src="<%=current_user.avatar_url%>" alt="a" style=" width: 100px; height: 100px">
      </div>
      <span class="fs-4 w-100 text-center"><%= current_user.full_name %></span>
    </div>
    <div class="d-flex justify-content-center">
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-1">
      <li>
        <figure class="px-1 py-3">
          <blockquote class="blockquote mb-4">
            <p class="h6"><i class="fas fa-quote-left fa-lg text-warning me-1"></i>
              <span class="font-italic">You know, sometimes I think I was born with a leak, and any goodness I started with just slowly spilled out of me and now it's all gone. And I'll never get it back in me. It's too late. Life is a series of closing doors, isn't it?</span></p>
          </blockquote>
          <figcaption class="blockquote-footer">Bojack Horseman</figcaption>
        </figure>
      </li>
    </ul>
    <hr>
    <div id="info" class="  p-2 d-flex flex-wrap gap-1 rounded">
      
      <span class="badge rounded-pill bg-primary">horse</span>
      <span class="badge rounded-pill bg-primary">saddle</span>
      <span class="badge rounded-pill bg-primary">food</span>
      <span class="badge rounded-pill bg-primary">wine</span>
      <span class="badge rounded-pill bg-primary">sleeping</span>
      <span class="badge rounded-pill bg-primary">humans</span>
      <span class="badge rounded-pill bg-primary">no dogs</span>
      <span class="badge rounded-pill bg-primary">emotional terrorism</span>
      <span class="badge rounded-pill bg-primary">regular terrorism</span>
    </div>
    <hr>
    <button type="button" class="btn btn-info"><%=  link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-primary" %></button>
  </div>
</div>